# Algorytmika i matematyka uczenia maszynowego 
## Laboratorium 4

Do wykonania laboratorium należy skorzystać z bibliotek:
- [numpy](https://numpy.org/)
- [matplotlib](https://matplotlib.org/)

### Zadanie 1

Dana jest następująca lista prostokątów:

```
rectangles = [("R1", 5, 4.5), ("Szeroki", 11, 3), ("R2", 4, 6), ("Wąski", 3, 8), ("Kwadrat 1", 5, 5), ("Kwadrat 2", 4.5, 4.5)] 
```

gdzie kolejne pola krotek to: 
- nazwa, 
- szerokość, 
- wysokość.

#### A) 
Na jej bazie utwórz ustrukturalizowaną tablicę Numpy (`np.array(...)`), następnie posortuj dane prostokąty rosnąco po polu, a w przypadku równości niech decyduje (alfabetycznie) nazwa prostokąta.

#### B) 
Wypisz posortowaną tablicę, w kolejności pól: 
1. szerokość, 
2. wysokość, 
3. nazwa.

> Uwaga: Gdzie to możliwe, działaj na typach i funkcjach z biblioteki Numpy.



In [15]:
import numpy as np
import matplotlib as pyplot

In [16]:
np_rec = np.array([("R1", 5., 4.5), ("Szeroki", 11., 3.), ("R2", 4., 6.), ("Wąski", 3., 8.), ("Kwadrat 1", 5., 5.), ("AA", 4., 6.), ("Kwadrat 2", 4.5, 4.5)])

In [17]:
print(np_rec)

[['R1' '5.0' '4.5']
 ['Szeroki' '11.0' '3.0']
 ['R2' '4.0' '6.0']
 ['Wąski' '3.0' '8.0']
 ['Kwadrat 1' '5.0' '5.0']
 ['AA' '4.0' '6.0']
 ['Kwadrat 2' '4.5' '4.5']]


In [18]:
def sort_by_field_and_name(x):
    return x[1].astype(float) * x[2].astype(float), x[0]

In [19]:
# np_rec[(np_rec[:, 1].astype(float) * np_rec[:, 2].astype(float)).argsort()]
print(np.array(sorted(np_rec, key=sort_by_field_and_name)))

[['Kwadrat 2' '4.5' '4.5']
 ['R1' '5.0' '4.5']
 ['AA' '4.0' '6.0']
 ['R2' '4.0' '6.0']
 ['Wąski' '3.0' '8.0']
 ['Kwadrat 1' '5.0' '5.0']
 ['Szeroki' '11.0' '3.0']]


In [20]:
np_rec[np_rec[:,1].argsort()]

array([['Szeroki', '11.0', '3.0'],
       ['Wąski', '3.0', '8.0'],
       ['R2', '4.0', '6.0'],
       ['AA', '4.0', '6.0'],
       ['Kwadrat 2', '4.5', '4.5'],
       ['R1', '5.0', '4.5'],
       ['Kwadrat 1', '5.0', '5.0']], dtype='<U32')

In [21]:
np_rec[np_rec[:,2].argsort()]

array([['Szeroki', '11.0', '3.0'],
       ['R1', '5.0', '4.5'],
       ['Kwadrat 2', '4.5', '4.5'],
       ['Kwadrat 1', '5.0', '5.0'],
       ['R2', '4.0', '6.0'],
       ['AA', '4.0', '6.0'],
       ['Wąski', '3.0', '8.0']], dtype='<U32')

In [22]:
np_rec[np_rec[:,0].argsort()]

array([['AA', '4.0', '6.0'],
       ['Kwadrat 1', '5.0', '5.0'],
       ['Kwadrat 2', '4.5', '4.5'],
       ['R1', '5.0', '4.5'],
       ['R2', '4.0', '6.0'],
       ['Szeroki', '11.0', '3.0'],
       ['Wąski', '3.0', '8.0']], dtype='<U32')

### Zadanie 2 - gra 2048

Dana jest kwadratowa plansza o boku `SIZE` (np. 4) dla znanej gry 2048 (https://2048game.com/pl/). 
Każdy wiersz zawiera od 0 do 4 liczb. Należy, z wykorzystaniem konstrukcji Numpy, zasymulować ruch w lewo, w prawo, w górę i w dół planszy zgodnie z regułami gry (ale **BEZ** dodawania nowego kafelka w losowym miejscu). Innymi słowy, trzeba napisać cztery funkcje: 
- `move_left(...)`, 
- `move_right(...)`, 
- `move_up(...)`, 
- `move_down(...)`.

Przykład ruchu w prawo:

Wejściem i wyjściem każdej z obu funkcji jest 2-wymiarowa tablica Numpy.

> UWAGA: postaraj się napisać funkcję tylko do jednego ruchu, a pozostałe trzy niech się do niej w sprytny sposób odwołują.

In [23]:
def move_left(board: np.ndarray) -> np.ndarray:
    for j in range(board.shape[0]):
        for i in range(1, board.shape[1]):
            if board[j, i] != 0:
                summed = False
                for k in range(i, 0, -1):
                    if board[j, k-1] == board[j, k] and not summed:
                        board[j, k-1] += board[j, k]
                        board[j, k] = 0
                        summed = True
                    if  board[j, k-1] == 0:
                        board[j, k-1] += board[j, k]
                        board[j, k] = 0
    return board

def move_right(board: np.ndarray) -> np.ndarray:
    return np.fliplr(move_left(np.fliplr(board)))

def move_down(board: np.ndarray) -> np.ndarray:
    return np.rot90(move_left(np.rot90(board, 3)))

def move_up(board: np.ndarray) -> np.ndarray:
    return np.flipud(move_down(np.flipud(board)))

In [29]:
SIZE = 4
board = np.array(([2,16,2,2],[8,0,0,4],[2,0,0,2],[4,4,4,4]))
print(board)

[[ 2 16  2  2]
 [ 8  0  0  4]
 [ 2  0  0  2]
 [ 4  4  4  4]]


In [30]:
print(move_right(board))

[[ 0  2 16  4]
 [ 0  0  8  4]
 [ 0  0  0  4]
 [ 0  0  8  8]]


In [31]:
print(move_down(board))

[[ 0  0  0  0]
 [ 0  0  0  4]
 [ 0  0  0  0]
 [ 0  2 32 16]]


In [32]:
print(move_left(board))

[[ 0  0  0  0]
 [ 4  0  0  0]
 [ 0  0  0  0]
 [ 2 32 16  0]]


In [33]:
print(move_up(board))

[[ 4 32 16  0]
 [ 2  0  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]]
